name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Classic Template
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.classic.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, repositories
        plugin_lines: yes
          
    - name: Coding Languages Indepth
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.languages.indepth.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_languages: yes
        plugin_languages_ignored: >-
          tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
        plugin_languages_indepth: yes
        plugin_languages_details: lines, bytes-size
        plugin_languages_limit: 8
        plugin_languages_analysis_timeout: 50
        
    - name: Full-year calendar
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.isocalendar.fullyear.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year

    - name: Recently starred repos
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.stars.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_stars: yes
        plugin_stars_limit: 3

    - name: Coding habits and activity
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.habits.charts.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: yes
        plugin_habits_days: 30
        plugin_habits_from: 500
        plugin_habits_languages_limit: 3
        config_timezone: Europe/Moscow

    - name: GitHub topics Labels
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.topics.svg
        token: NOT_NEEDED
        base: ""
        plugin_topics: yes
        plugin_topics_limit: 20

    - name: Featured repositories
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.repositories.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_repositories: yes
        plugin_repositories_featured: artexhibit/Kursvalut, artexhibit/igorcodes.ru, artexhibit/Fundamentals-of-algorithmization-and-programming

    - name: Achievements
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.achievements.compact.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_achievements: yes
        plugin_achievements_display: compact
        plugin_achievements_limit: 5

    - name: Recent activity
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.activity.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_activity: yes
        plugin_activity_limit: 3

    - name: Top answers from Stackoverflow
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.stackoverflow.svg
        token: NOT_NEEDED
        base: ""
        plugin_stackoverflow: yes
        plugin_stackoverflow_sections: answers-recent
        plugin_stackoverflow_limit: 1
        plugin_stackoverflow_user: 16471289

    - name: Apple Music - Random track from playlist
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.music.playlist.svg
        token: NOT_NEEDED
        base: ""
        plugin_music: yes
        plugin_music_playlist: https://embed.music.apple.com/ru/playlist/favorites/pl.u-XkD0vlEcD3RmMbW?l
        plugin_music_limit: 1

    - name: LeetCode statistics
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.leetcode.svg
        token: NOT_NEEDED
        base: ""
        plugin_leetcode: yes
        plugin_leetcode_user: artexhibit
        plugin_leetcode_sections: solved, skills
